# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImportCSV
                                 A QGIS plugin
 QGIS Import CSV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-04
        copyright            : (C) 2021 by MS
        email                : info@microsystem-j.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImportCSV class from file ImportCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .import_CSV import ImportCSV
    
    return ImportCSV(iface)
